<a href="https://colab.research.google.com/github/ShiftorTheOrca/asah-capstone/blob/leon/Asah_Fetch_A25_CS328.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Import Library**

In [22]:
# Library Essential
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
import shutil
from google.colab import files
from datetime import datetime

# Library pre-processing data
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

# Library save model (joblib)
import joblib

In [2]:
# Upload file .json untuk API key
files.upload()
print("API Key Received")

Saving kaggle.json to kaggle.json
API Key Received

In [3]:
os.makedirs('/root/.kaggle', exist_ok=True)

# Download dataset dari Kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json
!kaggle datasets download -d viridianachow/online-retail-uci-dataset
!kaggle datasets download -d mashlyn/online-retail-ii-uci

Dataset URL: https://www.kaggle.com/datasets/viridianachow/online-retail-uci-dataset
License(s): unknown
Downloading online-retail-uci-dataset.zip to /content
  0% 0.00/7.15M [00:00<?, ?B/s]
100% 7.15M/7.15M [00:00<00:00, 769MB/s]
Dataset URL: https://www.kaggle.com/datasets/mashlyn/online-retail-ii-uci
License(s): CC0-1.0
Downloading online-retail-ii-uci.zip to /content
  0% 0.00/14.5M [00:00<?, ?B/s]
100% 14.5M/14.5M [00:00<00:00, 831MB/s]

In [4]:
!unzip "online-retail-uci-dataset.zip"
!unzip "online-retail-ii-uci.zip"

Archive:  online-retail-uci-dataset.zip
  inflating: Online Retail.csv
Archive:  online-retail-ii-uci.zip
  inflating: online_retail_II.csv

# **Load Dataset**

In [5]:
df_1 = pd.read_csv('Online Retail.csv')
df_2 = pd.read_csv('online_retail_II.csv')

In [6]:
df_1.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [7]:
df_2.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

# **Exploratory**

In [8]:
column_names = ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'CustomerID', 'Country']
df_1.columns = df_2.columns = column_names

In [9]:
df_all = pd.concat([df_1, df_2])
df_all.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [10]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1609280 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1609280 non-null  object
 1   StockCode    1609280 non-null  object
 2   Description  1603444 non-null  object
 3   Quantity     1609280 non-null  int64
 4   InvoiceDate  1609280 non-null  object
 5   Price        1609280 non-null  float64
 6   CustomerID   1231193 non-null  float64
 7   Country      1609280 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 110.5+ MB

In [11]:
df_all = df_all.dropna()

In [12]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1231193 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1231193 non-null  object
 1   StockCode    1231193 non-null  object
 2   Description  1231193 non-null  object
 3   Quantity     1231193 non-null  int64
 4   InvoiceDate  1231193 non-null  object
 5   Price        1231193 non-null  float64
 6   CustomerID   1231193 non-null  float64
 7   Country      1231193 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 84.5+ MB

In [13]:
df_all = df_all.drop_duplicates()

In [14]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1199489 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1199489 non-null  object
 1   StockCode    1199489 non-null  object
 2   Description  1199489 non-null  object
 3   Quantity     1199489 non-null  int64
 4   InvoiceDate  1199489 non-null  object
 5   Price        1199489 non-null  float64
 6   CustomerID   1199489 non-null  float64
 7   Country      1199489 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 82.4+ MB

In [15]:
df_all.describe()

           Quantity         Price    CustomerID
count  1.199489e+06  1.199489e+06  1.199489e+06
mean   1.246246e+01  3.626171e+00  1.530238e+04
std    2.130975e+02  7.085152e+01  1.702425e+03
min   -8.099500e+04  0.000000e+00  1.234600e+04
25%    2.000000e+00  1.250000e+00  1.395600e+04
50%    5.000000e+00  1.950000e+00  1.519400e+04
75%    1.200000e+01  3.750000e+00  1.678800e+04
max    8.099500e+04  3.897000e+04  1.828700e+04

Konversi Satuan

In [39]:
date_string = "12/1/10 8:26"
date_format = "%m/%d/%y %H:%M"

# 2. Convert the string to a datetime object
date_object = datetime.strptime(date_string, date_format)

# 3. Convert the datetime object to an integer timestamp
integer_timestamp = int(date_object.timestamp())
print(integer_timestamp)

1291191960

In [40]:
tahun = 31556952
tahun *= 14
integer_timestamp += tahun
dt_object_local = datetime.fromtimestamp(integer_timestamp)
print(f"Local datetime from timestamp: {dt_object_local}")

Local datetime from timestamp: 2024-11-30 17:54:48

In [ ]:
# Encode kategorikal
label_encoder = LabelEncoder()
df_lencoder = pd.DataFrame(df_all['Invoice', 'StockCode', 'Quantity', 'InvoiceDate', 'Price', 'CustomerID', 'Country'])

# Pilih fitur kategorikal (dtype berupa object) untuk di-encode
category_features = df_all.select_dtypes(include=['object']).columns
for col in category_features:
    df_lencoder[col] = label_encoder.fit_transform(df[col])

plt.figure(figsize=(12, 10))
matrix_korelasi = df_lencoder.corr() # Method corr() milik DataFrame untuk mencari korelasi antar variabel

sns.heatmap(matrix_korelasi, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5, vmin=-1, vmax=1)
plt.title('Matrix Korelasi (seluruh fitur)')
plt.show()

In [41]:
print("Steve OTW DO")

Steve OTW DO